version: '3.7'

services:
  nodejs:
    container_name: nodejs
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
